nopCommerce-develop/src/Plugins/Nop.Plugin.Tax.Avalara/Models/Tax/TaxCategoryListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Tax.Avalara.Models.Tax
{
    /// <summary>
    /// Represents a tax category list model
    /// </summary>
    public class TaxCategoryListModel : BasePagedListModel<TaxCategoryModel>
    {
    }
}

nopCommerce-develop/src/Plugins/Nop.Plugin.Tax.Avalara/Models/Tax/TaxCategoryModel.cs
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.Tax.Avalara.Models.Tax
{
    /// <summary>
    /// Represents an extended tax category model
    /// </summary>
    public class TaxCategoryModel : Nop.Web.Areas.Admin.Models.Tax.TaxCategoryModel
    {
        #region Properties

        public string Description { get; set; }

        [NopResourceDisplayName("Plugins.Tax.Avalara.Fields.TaxCodeType")]
        public string TypeId { get; set; }
        public string Type { get; set; }

        #endregion
    }
}

nopCommerce-develop/src/Plugins/Nop.Plugin.Tax.Avalara/Models/Tax/TaxCategorySearchModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Tax.Avalara.Models.Tax
{
    /// <summary>
    /// Represents a tax category search model
    /// </summary>
    public class TaxCategorySearchModel : BaseSearchModel
    {
        #region Ctor

        public TaxCategorySearchModel()
        {
            AddTaxCategory = new TaxCategoryModel();
            AvailableTypes = new List<SelectListItem>();
        }

        #endregion

        #region Properties

        public TaxCategoryModel AddTaxCategory { get; set; }

        public IList<SelectListItem> AvailableTypes { get; set; }

        #endregion
    }
}

nopCommerce-develop/src/Plugins/Nop.Plugin.Tax.Avalara/Controllers/OverriddenTaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Avalara.AvaTax.RestClient;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Core;
using Nop.Core.Caching;
using Nop.Core.Domain.Tax;
using Nop.Plugin.Tax.Avalara.Services;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Services.Tax;
using Nop.Web.Areas.Admin.Controllers;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.Tax.Avalara.Controllers
{
    public class OverriddenTaxController : TaxController
    {
        #region Fields

        private readonly AvalaraTaxManager _avalaraTaxManager;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly IStaticCacheManager _cacheManager;
        private readonly ITaxCategoryService _taxCategoryService;
        private readonly ITaxPluginManager _taxPluginManager;

        #endregion

        #region Ctor

        public OverriddenTaxController(AvalaraTaxManager avalaraTaxManager,
            IGenericAttributeService genericAttributeService,
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ISettingService settingService,
            IStaticCacheManager cacheManager,
            ITaxCategoryService taxCategoryService,
            ITaxModelFactory taxModelFactory,
            ITaxPluginManager taxPluginManager,
            TaxSettings taxSettings) : base(permissionService,
                settingService,
                taxCategoryService,
                taxModelFactory,
                taxPluginManager,
                taxSettings)
        {
            _avalaraTaxManager = avalaraTaxManager;
            _genericAttributeService = genericAttributeService;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _cacheManager = cacheManager;
            _taxCategoryService = taxCategoryService;
            _taxPluginManager = taxPluginManager;
        }

        #endregion

        #region Methods

        public override IActionResult Categories()
        {
            //ensure that Avalara tax provider is active
            if (!_taxPluginManager.IsPluginActive(AvalaraTaxDefaults.SystemName))
            {
                //if isn't active return base action result
                RouteData.Values["controller"] = "Tax";
                return base.Categories();
            }

            if (!_permissionService.Authorize(StandardPermissionProvider.ManageTaxSettings))
                return AccessDeniedView();

            //prepare model
            var model = new Models.Tax.TaxCategorySearchModel();
            var taxCodeTypes = _cacheManager.Get(AvalaraTaxDefaults.TaxCodeTypesCacheKey, () => _avalaraTaxManager.GetTaxCodeTypes());
            if (taxCodeTypes != null)
                model.AvailableTypes = taxCodeTypes.Select(type => new SelectListItem(type.Value, type.Key)).ToList();
            model.SetGridPageSize();

            //use overridden view
            return View("~/Plugins/Tax.Avalara/Views/Tax/Categories.cshtml", model);
        }

        [HttpPost]
        public IActionResult TaxCategoryUpdate(Models.Tax.TaxCategoryModel model)
        {
            return base.CategoryUpdate(model);
        }

        [HttpPost]
        public IActionResult TaxCategoryAdd(Models.Tax.TaxCategoryModel model)
        {
            //ensure that Avalara tax provider is active
            if (!_taxPluginManager.IsPluginActive(AvalaraTaxDefaults.SystemName))
                return new NullJsonResult();

            if (!_permissionService.Authorize(StandardPermissionProvider.ManageTaxSettings))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return ErrorJson(ModelState.SerializeErrors());

            var taxCategory = new TaxCategory();
            taxCategory = model.ToEntity(taxCategory);
            _taxCategoryService.InsertTaxCategory(taxCategory);

            //save tax code type as generic attribute
            if (!string.IsNullOrEmpty(model.TypeId) && !model.TypeId.Equals(Guid.Empty.ToString()))
                _genericAttributeService.SaveAttribute(taxCategory, AvalaraTaxDefaults.TaxCodeTypeAttribute, model.TypeId);

            return Json(new { Result = true });
        }

        [HttpPost]
        public override IActionResult CategoryDelete(int id)
        {
            //ensure that Avalara tax provider is active
            if (!_taxPluginManager.IsPluginActive(AvalaraTaxDefaults.SystemName))
                return new NullJsonResult();

            if (!_permissionService.Authorize(StandardPermissionProvider.ManageTaxSettings))
                return AccessDeniedView();

            //try to get a tax category with the specified id
            var taxCategory = _taxCategoryService.GetTaxCategoryById(id);
            if (taxCategory == null)
                throw new ArgumentException("No tax category found with the specified id");

            //delete generic attributes 
            _genericAttributeService.SaveAttribute<string>(taxCategory, AvalaraTaxDefaults.TaxCodeDescriptionAttribute, null);
            _genericAttributeService.SaveAttribute<string>(taxCategory, AvalaraTaxDefaults.TaxCodeTypeAttribute, null);

            _taxCategoryService.DeleteTaxCategory(taxCategory);

            return new NullJsonResult();
        }

        [HttpPost, ActionName("Categories")]
        [FormValueRequired("importTaxCodes")]
        public IActionResult ImportTaxCodes()
        {
            //ensure that Avalara tax provider is active
            if (!_taxPluginManager.IsPluginActive(AvalaraTaxDefaults.SystemName))
                return Categories();

            if (!_permissionService.Authorize(StandardPermissionProvider.ManageTaxSettings))
                return AccessDeniedView();

            //get Avalara pre-defined system tax codes (only active)
            var systemTaxCodes = _avalaraTaxManager.GetSystemTaxCodes(true);
            if (!systemTaxCodes?.Any() ?? true)
            {
                _notificationService.ErrorNotification(_localizationService.GetResource("Plugins.Tax.Avalara.TaxCodes.Import.Error"));
                return Categories();
            }

            //get existing tax categories
            var existingTaxCategories = _taxCategoryService.GetAllTaxCategories().Select(taxCategory => taxCategory.Name).ToList();

            //remove duplicates
            var taxCodesToImport = systemTaxCodes.Where(taxCode => !existingTaxCategories.Contains(taxCode.taxCode)).ToList();

            var importedTaxCodesNumber = 0;
            foreach (var taxCode in taxCodesToImport)
            {
                if (string.IsNullOrEmpty(taxCode?.taxCode))
                    continue;

                //create new tax category
                var taxCategory = new TaxCategory { Name = taxCode.taxCode };
                _taxCategoryService.InsertTaxCategory(taxCategory);

                //save description and type
                if (!string.IsNullOrEmpty(taxCode.description))
                    _genericAttributeService.SaveAttribute(taxCategory, AvalaraTaxDefaults.TaxCodeDescriptionAttribute, taxCode.description);
                if (!string.IsNullOrEmpty(taxCode.taxCodeTypeId))
                    _genericAttributeService.SaveAttribute(taxCategory, AvalaraTaxDefaults.TaxCodeTypeAttribute, taxCode.taxCodeTypeId);

                importedTaxCodesNumber++;
            }

            //successfully imported
            var successMessage = _localizationService.GetResource("Plugins.Tax.Avalara.TaxCodes.Import.Success");
            _notificationService.SuccessNotification(string.Format(successMessage, importedTaxCodesNumber));

            return Categories();
        }

        [HttpPost, ActionName("Categories")]
        [FormValueRequired("exportTaxCodes")]
        public IActionResult ExportTaxCodes()
        {
            //ensure that Avalara tax provider is active
            if (!_taxPluginManager.IsPluginActive(AvalaraTaxDefaults.SystemName))
                return Categories();

            if (!_permissionService.Authorize(StandardPermissionProvider.ManageTaxSettings))
                return AccessDeniedView();

            //prepare tax codes to export
            var taxCodesToExport = _taxCategoryService.GetAllTaxCategories().Select(taxCategory => new TaxCodeModel
            {
                createdDate = DateTime.UtcNow,
                description = CommonHelper.EnsureMaximumLength(taxCategory.Name, 255),
                isActive = true,
                taxCode = CommonHelper.EnsureMaximumLength(taxCategory.Name, 25),
                taxCodeTypeId = CommonHelper.EnsureMaximumLength(_genericAttributeService
                    .GetAttribute<string>(taxCategory, AvalaraTaxDefaults.TaxCodeTypeAttribute) ?? "P", 2)
            }).Where(taxCode => !string.IsNullOrEmpty(taxCode.taxCode)).ToList();

            //get existing tax codes (only active)
            var existingTaxCodes = _avalaraTaxManager.GetTaxCodes(true)?.Select(taxCode => taxCode.taxCode).ToList() ?? new List<string>();

            //add Avalara pre-defined system tax codes
            var systemTaxCodes = _avalaraTaxManager.GetSystemTaxCodes(true)?.Select(taxCode => taxCode.taxCode).ToList() ?? new List<string>();

nopCommerce-develop/src/Plugins/Nop.Plugin.Tax.Avalara/Views/Tax/Categories.cshtml
@model Nop.Plugin.Tax.Avalara.Models.Tax.TaxCategorySearchModel

@using Nop.Web.Framework.Infrastructure
@using Nop.Web.Framework.UI
@{
    Layout = "_AdminLayout";

    //page title
    ViewBag.Title = T("Admin.Configuration.Tax.Categories").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Tax categories");
}

<form asp-controller="OverriddenTax" asp-action="Categories" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Configuration.Tax.Categories")
        </h1>
    </div>

    <div class="content">
        <div class="form-horizontal">
            <div class="panel-group">
                @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.TaxCategoryListButtons })
                <div class="panel panel-default">
                    <div class="panel-body">
                        @await Html.PartialAsync("Table", new DataTablesModel
                        {
                            Name = "tax-categories-grid",
                            UrlRead = new DataUrl("Categories", "OverriddenTax", null),
                            UrlDelete = new DataUrl("CategoryDelete", "OverriddenTax", null),
                            UrlUpdate = new DataUrl("TaxCategoryUpdate", "OverriddenTax", null),
                            Length = Model.PageSize,
                            LengthMenu = Model.AvailablePageSizes,
                            ColumnCollection = new List<ColumnProperty>
                            {
                                new ColumnProperty(nameof(Nop.Plugin.Tax.Avalara.Models.Tax.TaxCategoryModel.Name))
                                {
                                    Title = T("Admin.Configuration.Tax.Categories.Fields.Name").Text,
                                    Width = "300",
                                    Editable = true,
                                    EditType = EditType.String
                                },
                                new ColumnProperty(nameof(Nop.Plugin.Tax.Avalara.Models.Tax.TaxCategoryModel.DisplayOrder))
                                {
                                    Title = T("Admin.Configuration.Tax.Categories.Fields.DisplayOrder").Text,
                                    Width = "100",
                                    ClassName = NopColumnClassDefaults.CenterAll,
                                    Editable = true,
                                    EditType = EditType.Number
                                },
                                new ColumnProperty(nameof(Nop.Plugin.Tax.Avalara.Models.Tax.TaxCategoryModel.Type))
                                {
                                    Title = T("Plugins.Tax.Avalara.Fields.TaxCodeType").Text,
                                    Width = "100",
                                    ClassName = NopColumnClassDefaults.CenterAll,
                                },
                                new ColumnProperty(nameof(Nop.Plugin.Tax.Avalara.Models.Tax.TaxCategoryModel.Description))
                                {
                                    Title = T("Plugins.Tax.Avalara.Fields.TaxCodeDescription").Text
                                },
                                new ColumnProperty(nameof(TaxCategoryModel.Id))
                                {
                                    Title = T("Admin.Common.Edit").Text,
                                    Width = "100",
                                    ClassName =  NopColumnClassDefaults.Button,
                                    Render = new RenderButtonsInlineEdit()
                                },
                                new ColumnProperty(nameof(TaxCategoryModel.Id))
                                {
                                    Title = T("Admin.Common.Delete").Text,
                                    Width = "100",
                                    Render = new RenderButtonRemove(T("Admin.Common.Delete").Text),
                                    ClassName = NopColumnClassDefaults.Button
                                }
                            }
                        })

                        <div class="panel panel-default">
                            <div class="panel-heading">
                                @T("Admin.Common.AddNewRecord")
                            </div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <div class="col-md-3">
                                        <nop-label asp-for="@Model.AddTaxCategory.Name" />
                                    </div>
                                    <div class="col-md-9">
                                        <nop-editor asp-for="@Model.AddTaxCategory.Name" />
                                        <span asp-validation-for="@Model.AddTaxCategory.Name"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-3">
                                        <nop-label asp-for="@Model.AddTaxCategory.DisplayOrder" />
                                    </div>
                                    <div class="col-md-9">
                                        <nop-editor asp-for="@Model.AddTaxCategory.DisplayOrder" />
                                        <span asp-validation-for="@Model.AddTaxCategory.DisplayOrder"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-3">
                                        <nop-label asp-for="@Model.AddTaxCategory.TypeId" />
                                    </div>
                                    <div class="col-md-9">
                                        <nop-select asp-for="@Model.AddTaxCategory.TypeId" asp-items="@Model.AvailableTypes" />
                                        <span asp-validation-for="@Model.AddTaxCategory.TypeId"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-9 col-md-offset-3">
                                        <button type="button" id="addTaxCategory" class="btn btn-primary">@T("Admin.Common.AddNewRecord")</button>
                                    </div>
                                </div>
                            </div>
                            <script>
                                $(document).ready(function () {
                                    $('#addTaxCategory').click(function () {
                                        $('#addTaxCategory').attr('disabled', true);
                                        var postData = {
                                            Name: $("#@Html.IdFor(model => model.AddTaxCategory.Name)").val(),
                                            DisplayOrder: $("#@Html.IdFor(model => model.AddTaxCategory.DisplayOrder)").val(),
                                            TypeId: $("#@Html.IdFor(model => model.AddTaxCategory.TypeId)").val()
                                        };
                                        addAntiForgeryToken(postData);

                                        $.ajax({
                                            cache: false,
                                            type: "POST",
                                            url: "@Html.Raw(Url.Action("TaxCategoryAdd", "OverriddenTax", null))",
                                            data: postData,
                                            success: function (data, textStatus, jqXHR) {
                                                if (data.Result) {
                                                    updateTable('#tax-categories-grid');
                                                } else {
                                                    //display errors if returned
                                                    display_nop_error(data);
                                                }
                                            },
                                            complete: function (jqXHR, textStatus) {
                                                $('#addTaxCategory').attr('disabled', false);
                                                $("#@Html.IdFor(model => model.AddTaxCategory.Name)").val('');
                                                $("#@Html.IdFor(model => model.AddTaxCategory.DisplayOrder)").val('');
                                                $("#@Html.IdFor(model => model.AddTaxCategory.TypeId)").val('');
                                            }
                                        });
                                    });
                                });
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

nopCommerce-develop/src/Plugins/Nop.Plugin.Tax.Avalara/Views/Tax/TaxCodes.cshtml
<div class="btn-group">
    <button type="button" class="btn btn-warning">
        <i class="fa fa-exchange"></i>
        @T("Plugins.Tax.Avalara.TaxCodes")
    </button>
    <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        <span class="caret"></span>
        <span class="sr-only">&nbsp;</span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li>
            <button type="submit" name="exportTaxCodes">
                <i class="fa fa-exchange"></i>
                @T("Plugins.Tax.Avalara.TaxCodes.Export")
            </button>
        </li>
        <li>
            <button type="submit" name="importTaxCodes">
                <i class="fa fa-exchange"></i>
                @T("Plugins.Tax.Avalara.TaxCodes.Import")
            </button>
        </li>
        <li class="divider"></li>
        <li>
            <button type="submit" name="deleteTaxCodes">
                <i class="fa fa-trash-o"></i>
                @T("Plugins.Tax.Avalara.TaxCodes.Delete")
            </button>
        </li>
    </ul>
</div>