nopCommerce-develop/src/Presentation/Nop.Web/Areas/Admin/Controllers/DownloadController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Media;
using Nop.Core.Infrastructure;
using Nop.Services.Logging;
using Nop.Services.Media;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class DownloadController : BaseAdminController
    {
        #region Fields

        private readonly IDownloadService _downloadService;
        private readonly ILogger _logger;
        private readonly INopFileProvider _fileProvider;
        private readonly IWorkContext _workContext;

        #endregion

        #region Ctor

        public DownloadController(IDownloadService downloadService,
            ILogger logger,
            INopFileProvider fileProvider,
            IWorkContext workContext)
        {
            _downloadService = downloadService;
            _logger = logger;
            _fileProvider = fileProvider;
            _workContext = workContext;
        }

        #endregion

        #region Methods

        public virtual IActionResult DownloadFile(Guid downloadGuid)
        {
            var download = _downloadService.GetDownloadByGuid(downloadGuid);
            if (download == null)
                return Content("No download record found with the specified id");

            if (download.UseDownloadUrl)
                return new RedirectResult(download.DownloadUrl);

            //use stored data
            if (download.DownloadBinary == null)
                return Content($"Download data is not available any more. Download GD={download.Id}");

            var fileName = !string.IsNullOrWhiteSpace(download.Filename) ? download.Filename : download.Id.ToString();
            var contentType = !string.IsNullOrWhiteSpace(download.ContentType)
                ? download.ContentType
                : MimeTypes.ApplicationOctetStream;
            return new FileContentResult(download.DownloadBinary, contentType)
            {
                FileDownloadName = fileName + download.Extension
            };
        }

        [HttpPost]
        //do not validate request token (XSRF)
        [AdminAntiForgery(true)]
        public virtual IActionResult SaveDownloadUrl(string downloadUrl)
        {
            //don't allow to save empty download object
            if (string.IsNullOrEmpty(downloadUrl))
            {
                return Json(new
                {
                    success = false,
                    message = "Please enter URL"
                });
            }

            //insert
            var download = new Download
            {
                DownloadGuid = Guid.NewGuid(),
                UseDownloadUrl = true,
                DownloadUrl = downloadUrl,
                IsNew = true
            };
            _downloadService.InsertDownload(download);

            return Json(new { success = true, downloadId = download.Id });
        }

        [HttpPost]
        //do not validate request token (XSRF)
        [AdminAntiForgery(true)]
        public virtual IActionResult AsyncUpload()
        {
            var httpPostedFile = Request.Form.Files.FirstOrDefault();
            if (httpPostedFile == null)
            {
                return Json(new
                {
                    success = false,
                    message = "No file uploaded"
                });
            }

            var fileBinary = _downloadService.GetDownloadBits(httpPostedFile);

            var qqFileNameParameter = "qqfilename";
            var fileName = httpPostedFile.FileName;
            if (string.IsNullOrEmpty(fileName) && Request.Form.ContainsKey(qqFileNameParameter))
                fileName = Request.Form[qqFileNameParameter].ToString();
            //remove path (passed in IE)
            fileName = _fileProvider.GetFileName(fileName);

            var contentType = httpPostedFile.ContentType;

            var fileExtension = _fileProvider.GetFileExtension(fileName);
            if (!string.IsNullOrEmpty(fileExtension))
                fileExtension = fileExtension.ToLowerInvariant();

            var download = new Download
            {
                DownloadGuid = Guid.NewGuid(),
                UseDownloadUrl = false,
                DownloadUrl = string.Empty,
                DownloadBinary = fileBinary,
                ContentType = contentType,
                //we store filename without extension for downloads
                Filename = _fileProvider.GetFileNameWithoutExtension(fileName),
                Extension = fileExtension,
                IsNew = true
            };

            try
            {
                _downloadService.InsertDownload(download);

                //when returning JSON the mime-type must be set to text/plain
                //otherwise some browsers will pop-up a "Save As" dialog.
                return Json(new
                {
                    success = true,
                    downloadId = download.Id,
                    downloadUrl = Url.Action("DownloadFile", new { downloadGuid = download.DownloadGuid })
                });
            }
            catch (Exception exc)
            {
                _logger.Error(exc.Message, exc, _workContext.CurrentCustomer);

                return Json(new
                {
                    success = false,
                    message = "File cannot be saved"
                });
            }
        }

        #endregion
    }
}

nopCommerce-develop/src/Presentation/Nop.Web/Areas/Admin/Controllers/PictureController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Nop.Services.Media;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class PictureController : BaseAdminController
    {
        #region Fields

        private readonly IPictureService _pictureService;

        #endregion

        #region Ctor

        public PictureController(IPictureService pictureService)
        {
            _pictureService = pictureService;
        }

        #endregion

        #region Methods

        [HttpPost]
        //do not validate request token (XSRF)
        [AdminAntiForgery(true)]
        public virtual IActionResult AsyncUpload()
        {
            //if (!_permissionService.Authorize(StandardPermissionProvider.UploadPictures))
            //    return Json(new { success = false, error = "You do not have required permissions" }, "text/plain");

            var httpPostedFile = Request.Form.Files.FirstOrDefault();
            if (httpPostedFile == null)
            {
                return Json(new
                {
                    success = false,
                    message = "No file uploaded"
                });
            }

            const string qqFileNameParameter = "qqfilename";

            var qqFileName = Request.Form.ContainsKey(qqFileNameParameter)
                ? Request.Form[qqFileNameParameter].ToString()
                : string.Empty;

            var picture = _pictureService.InsertPicture(httpPostedFile, qqFileName);

            //when returning JSON the mime-type must be set to text/plain
            //otherwise some browsers will pop-up a "Save As" dialog.
            return Json(new
            {
                success = true,
                pictureId = picture.Id,
                imageUrl = _pictureService.GetPictureUrl(picture, 100)
            });
        }

        #endregion
    }
}

nopCommerce-develop/src/Presentation/Nop.Web/Controllers/CountryController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Web.Factories;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Controllers
{
    public partial class CountryController : BasePublicController
	{
        #region Fields

        private readonly ICountryModelFactory _countryModelFactory;
        
        #endregion
        
        #region Ctor

        public CountryController(ICountryModelFactory countryModelFactory)
		{
            _countryModelFactory = countryModelFactory;
		}
        
        #endregion
        
        #region States / provinces

        //available even when navigation is not allowed
        [CheckAccessPublicStore(true)]
        public virtual IActionResult GetStatesByCountryId(string countryId, bool addSelectStateItem)
        {
            var model = _countryModelFactory.GetStatesByCountryId(countryId, addSelectStateItem);
            return Json(model);
        }
        
        #endregion
    }
}

nopCommerce-develop/src/Presentation/Nop.Web/Controllers/DownloadController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Customers;
using Nop.Services.Catalog;
using Nop.Services.Localization;
using Nop.Services.Media;
using Nop.Services.Orders;

namespace Nop.Web.Controllers
{
    public partial class DownloadController : BasePublicController
    {
        private readonly CustomerSettings _customerSettings;
        private readonly IDownloadService _downloadService;
        private readonly ILocalizationService _localizationService;
        private readonly IOrderService _orderService;
        private readonly IProductService _productService;
        private readonly IWorkContext _workContext;

        public DownloadController(CustomerSettings customerSettings,
            IDownloadService downloadService,
            ILocalizationService localizationService,
            IOrderService orderService,
            IProductService productService,
            IWorkContext workContext)
        {
            _customerSettings = customerSettings;
            _downloadService = downloadService;
            _localizationService = localizationService;
            _orderService = orderService;
            _productService = productService;
            _workContext = workContext;
        }
        
        public virtual IActionResult Sample(int productId)
        {
            var product = _productService.GetProductById(productId);
            if (product == null)
                return InvokeHttp404();

            if (!product.HasSampleDownload)
                return Content("Product doesn't have a sample download.");

            var download = _downloadService.GetDownloadById(product.SampleDownloadId);
            if (download == null)
                return Content("Sample download is not available any more.");

            if (download.UseDownloadUrl)
                return new RedirectResult(download.DownloadUrl);
            
            if (download.DownloadBinary == null)
                return Content("Download data is not available any more.");
            
            var fileName = !string.IsNullOrWhiteSpace(download.Filename) ? download.Filename : product.Id.ToString();
            var contentType = !string.IsNullOrWhiteSpace(download.ContentType) ? download.ContentType : MimeTypes.ApplicationOctetStream;
            return new FileContentResult(download.DownloadBinary, contentType) { FileDownloadName = fileName + download.Extension }; 
        }

        public virtual IActionResult GetDownload(Guid orderItemId, bool agree = false)
        {
            var orderItem = _orderService.GetOrderItemByGuid(orderItemId);
            if (orderItem == null)
                return InvokeHttp404();

            var order = orderItem.Order;
            var product = orderItem.Product;
            if (!_downloadService.IsDownloadAllowed(orderItem))
                return Content("Downloads are not allowed");

            if (_customerSettings.DownloadableProductsValidateUser)
            {
                if (_workContext.CurrentCustomer == null)
                    return Challenge();

                if (order.CustomerId != _workContext.CurrentCustomer.Id)
                    return Content("This is not your order");
            }

            var download = _downloadService.GetDownloadById(product.DownloadId);
            if (download == null)
                return Content("Download is not available any more.");

            if (product.HasUserAgreement && !agree)
                return RedirectToRoute("DownloadUserAgreement", new { orderItemId = orderItemId });


            if (!product.UnlimitedDownloads && orderItem.DownloadCount >= product.MaxNumberOfDownloads)
                return Content(string.Format(_localizationService.GetResource("DownloadableProducts.ReachedMaximumNumber"), product.MaxNumberOfDownloads));
           
            if (download.UseDownloadUrl)
            {
                //increase download
                orderItem.DownloadCount++;
                _orderService.UpdateOrder(order);

                //return result
                return new RedirectResult(download.DownloadUrl);
            }
            
            //binary download
            if (download.DownloadBinary == null)
                    return Content("Download data is not available any more.");

            //increase download
            orderItem.DownloadCount++;
            _orderService.UpdateOrder(order);

            //return result
            var fileName = !string.IsNullOrWhiteSpace(download.Filename) ? download.Filename : product.Id.ToString();
            var contentType = !string.IsNullOrWhiteSpace(download.ContentType) ? download.ContentType : MimeTypes.ApplicationOctetStream;
            return new FileContentResult(download.DownloadBinary, contentType) { FileDownloadName = fileName + download.Extension };  
        }

        public virtual IActionResult GetLicense(Guid orderItemId)
        {
            var orderItem = _orderService.GetOrderItemByGuid(orderItemId);
            if (orderItem == null)
                return InvokeHttp404();

            var order = orderItem.Order;
            var product = orderItem.Product;
            if (!_downloadService.IsLicenseDownloadAllowed(orderItem))
                return Content("Downloads are not allowed");

            if (_customerSettings.DownloadableProductsValidateUser)
            {
                if (_workContext.CurrentCustomer == null || order.CustomerId != _workContext.CurrentCustomer.Id)
                    return Challenge();
            }

            var download = _downloadService.GetDownloadById(orderItem.LicenseDownloadId.HasValue ? orderItem.LicenseDownloadId.Value : 0);
            if (download == null)
                return Content("Download is not available any more.");
            
            if (download.UseDownloadUrl)
                return new RedirectResult(download.DownloadUrl);

            //binary download
            if (download.DownloadBinary == null)
                return Content("Download data is not available any more.");
                
            //return result
            var fileName = !string.IsNullOrWhiteSpace(download.Filename) ? download.Filename : product.Id.ToString();
            var contentType = !string.IsNullOrWhiteSpace(download.ContentType) ? download.ContentType : MimeTypes.ApplicationOctetStream;
            return new FileContentResult(download.DownloadBinary, contentType) { FileDownloadName = fileName + download.Extension };
        }

        public virtual IActionResult GetFileUpload(Guid downloadId)
        {
            var download = _downloadService.GetDownloadByGuid(downloadId);
            if (download == null)
                return Content("Download is not available any more.");

            if (download.UseDownloadUrl)
                return new RedirectResult(download.DownloadUrl);

            //binary download
            if (download.DownloadBinary == null)
                return Content("Download data is not available any more.");

            //return result
            var fileName = !string.IsNullOrWhiteSpace(download.Filename) ? download.Filename : downloadId.ToString();
            var contentType = !string.IsNullOrWhiteSpace(download.ContentType) ? download.ContentType : MimeTypes.ApplicationOctetStream;
            return new FileContentResult(download.DownloadBinary, contentType) { FileDownloadName = fileName + download.Extension };
        }

        public virtual IActionResult GetOrderNoteFile(int orderNoteId)
        {
            var orderNote = _orderService.GetOrderNoteById(orderNoteId);
            if (orderNote == null)
                return InvokeHttp404();

            var order = orderNote.Order;

            if (_workContext.CurrentCustomer == null || order.CustomerId != _workContext.CurrentCustomer.Id)
                return Challenge();

            var download = _downloadService.GetDownloadById(orderNote.DownloadId);
            if (download == null)
                return Content("Download is not available any more.");

            if (download.UseDownloadUrl)
                return new RedirectResult(download.DownloadUrl);

            //binary download
            if (download.DownloadBinary == null)
                return Content("Download data is not available any more.");

            //return result
            var fileName = !string.IsNullOrWhiteSpace(download.Filename) ? download.Filename : orderNote.Id.ToString();
            var contentType = !string.IsNullOrWhiteSpace(download.ContentType) ? download.ContentType : MimeTypes.ApplicationOctetStream;
            return new FileContentResult(download.DownloadBinary, contentType) { FileDownloadName = fileName + download.Extension };
        }
    }
}

nopCommerce-develop/src/Presentation/Nop.Web/Areas/Admin/Views/Shared/EditorTemplates/Address.cshtml
@model AddressModel

@if (Model.CountryEnabled && Model.StateProvinceEnabled)
{
    <script>
        $(document).ready(function () {
            $("#@Html.IdFor(model => model.CountryId)").change(function () {
                var selectedItem = $(this).val();
                var ddlStates = $("#@Html.IdFor(model => model.StateProvinceId)");
                $.ajax({
                    cache: false,
                    type: "GET",
                    url: "@(Url.Action("GetStatesByCountryId", "Country"))",
                    data: {
                        "countryId": selectedItem,
                        "addSelectStateItem": "false"
                    },
                    success: function (data, textStatus, jqXHR) {
                        ddlStates.html('');
                        $.each(data, function (id, option) {
                            ddlStates.append($('<option></option>').val(option.id).html(option.name));
                        });
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        $("#statesAlert").click();
                    }
                });
            });
        });
    </script>
}
<input asp-for="Id" type="hidden" />
<input asp-for="FirstNameEnabled" type="hidden" />
<input asp-for="FirstNameRequired" type="hidden" />
<input asp-for="LastNameEnabled" type="hidden" />
<input asp-for="LastNameRequired" type="hidden" />
<input asp-for="EmailEnabled" type="hidden" />
<input asp-for="EmailRequired" type="hidden" />
<input asp-for="CompanyEnabled" type="hidden" />
<input asp-for="CompanyRequired" type="hidden" />
<input asp-for="CountryEnabled" type="hidden" />
<input asp-for="CountryRequired" type="hidden" />
<input asp-for="StateProvinceEnabled" type="hidden" />
<input asp-for="CountyEnabled" type="hidden" />
<input asp-for="CountyRequired" type="hidden" />
<input asp-for="CityEnabled" type="hidden" />
<input asp-for="CityRequired" type="hidden" />
<input asp-for="StreetAddressEnabled" type="hidden" />
<input asp-for="StreetAddressRequired" type="hidden" />
<input asp-for="StreetAddress2Enabled" type="hidden" />
<input asp-for="StreetAddress2Required" type="hidden" />
<input asp-for="ZipPostalCodeEnabled" type="hidden" />
<input asp-for="ZipPostalCodeRequired" type="hidden" />
<input asp-for="PhoneEnabled" type="hidden" />
<input asp-for="PhoneRequired" type="hidden" />
<input asp-for="FaxEnabled" type="hidden" />
<input asp-for="FaxRequired" type="hidden" />
@if (Model.FirstNameEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="FirstName" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="FirstName" asp-required="@Model.FirstNameRequired" />
            <span asp-validation-for="FirstName"></span>
        </div>
    </div>
}
@if (Model.LastNameEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="LastName" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="LastName" asp-required="@Model.LastNameRequired" />
            <span asp-validation-for="LastName"></span>
        </div>
    </div>
}
@if (Model.EmailEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="Email" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="Email" asp-required="@Model.EmailRequired" />
            <span asp-validation-for="Email"></span>
        </div>
    </div>
}
@if (Model.CompanyEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="Company" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="Company" asp-required="@Model.CompanyRequired" />
            <span asp-validation-for="Company"></span>
        </div>
    </div>
}
@if (Model.CountryEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="CountryId" />
        </div>
        <div class="col-md-9">
            <nop-select asp-for="CountryId" asp-items="Model.AvailableCountries" asp-required="@Model.CountryRequired" />
            <span asp-validation-for="CountryId"></span>
        </div>
    </div>
}
@if (Model.CountryEnabled && Model.StateProvinceEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="StateProvinceId" />
        </div>
        <div class="col-md-9">
            <nop-select asp-for="StateProvinceId" asp-items="Model.AvailableStates" />
            <span asp-validation-for="StateProvinceId"></span>
        </div>
    </div>
}
@if (Model.CountyEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="County" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="County" asp-required="@Model.CountyRequired" />
            <span asp-validation-for="County"></span>
        </div>
    </div>
}
@if (Model.CityEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="City" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="City" asp-required="@Model.CityRequired" />
            <span asp-validation-for="City"></span>
        </div>
    </div>
}
@if (Model.StreetAddressEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="Address1" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="Address1" asp-required="@Model.StreetAddressRequired" />
            <span asp-validation-for="Address1"></span>
        </div>
    </div>
}
@if (Model.StreetAddress2Enabled)
{
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="Address2" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="Address2" asp-required="@Model.StreetAddress2Required" />
            <span asp-validation-for="Address2"></span>
        </div>
    </div>
}
@if (Model.ZipPostalCodeEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="ZipPostalCode" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="ZipPostalCode" asp-required="@Model.ZipPostalCodeRequired" />
            <span asp-validation-for="ZipPostalCode"></span>
        </div>
    </div>
}
@if (Model.PhoneEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="PhoneNumber" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="PhoneNumber" asp-required="@Model.PhoneRequired" />
            <span asp-validation-for="PhoneNumber"></span>
        </div>
    </div>
}
@if (Model.FaxEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="FaxNumber" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="FaxNumber" asp-required="@Model.FaxRequired" />
            <span asp-validation-for="FaxNumber"></span>
        </div>
    </div>
}
@if (Model.CustomAddressAttributes.Count > 0)
{
    @await Html.PartialAsync("_AddressAttributes", Model.CustomAddressAttributes)
}
<nop-alert asp-alert-id="statesAlert" asp-alert-message="@T("Admin.Common.Alert.States.Failed")" />

nopCommerce-develop/src/Presentation/Nop.Web/Areas/Admin/Views/Shared/EditorTemplates/Date.cshtml
@model DateTime
<input id="@Html.IdForModel()" name="@Html.NameForModel()" value="@((Model > DateTime.MinValue ? Model : DateTime.Today).ToShortDateString())" />
<script>
    $(document).ready(function () {
        $("#@Html.IdForModel()").kendoDatePicker();
    });
</script>

nopCommerce-develop/src/Presentation/Nop.Web/Areas/Admin/Views/Shared/EditorTemplates/DateNullable.cshtml
@model DateTime?
<input id="@Html.IdForModel()" name="@Html.NameForModel()" value="@(Model > DateTime.MinValue || Model.HasValue ? Model.Value.ToShortDateString() : null)" />
<script>
    $(document).ready(function () {
        $("#@Html.IdForModel()").kendoDatePicker();
    });
</script>

nopCommerce-develop/src/Presentation/Nop.Web/Areas/Admin/Views/Shared/EditorTemplates/DateTime.cshtml
@model DateTime
@using System.Globalization
<input id="@Html.IdForModel()" name="@Html.NameForModel()" value="@((Model > DateTime.MinValue ? Model : DateTime.Today).ToString(CultureInfo.CurrentCulture.DateTimeFormat))" />
<script>
    $(document).ready(function () {
        $("#@Html.IdForModel()").kendoDateTimePicker({
            popup: {
                position: "bottom right",
                origin: "top right"
            }
        });
    });
</script>

nopCommerce-develop/src/Presentation/Nop.Web/Areas/Admin/Views/Shared/EditorTemplates/DateTimeNullable.cshtml
@model DateTime?
@using System.Globalization
<input id="@Html.IdForModel()" name="@Html.NameForModel()" value="@(Model > DateTime.MinValue || Model.HasValue ? Model.Value.ToString(CultureInfo.CurrentCulture.DateTimeFormat) : null)" />
<script>
    $(document).ready(function () {
        $("#@Html.IdForModel()").kendoDateTimePicker({
            popup: {
                position: "bottom right",
                origin: "top right"
            }
        });
    });
</script>

nopCommerce-develop/src/Presentation/Nop.Web/Areas/Admin/Views/Shared/EditorTemplates/Decimal.cshtml
@model Decimal
<input asp-for="@Model" asp-format="{0:F4}" />
@{
    var postfix = "";
    if (ViewData.ContainsKey("postfix") && ViewData["postfix"] != null)
    {
        postfix = ViewData["postfix"].ToString();
    }
}
<script>
    $(document).ready(function() {
        $("#@Html.IdForModel()").TouchSpin({
            min: @Html.Raw(decimal.MinValue),
            max: @Html.Raw(decimal.MaxValue),
            decimals: 4, //always display 4 digits
            forcestepdivisibility: "none",
            verticalbuttons: true,
            verticalupclass: "glyphicon glyphicon-chevron-up",
            verticaldownclass: "glyphicon glyphicon-chevron-down",
            buttondown_class: "btn",
            buttonup_class: "btn",
            postfix: "@postfix"
        });
    });
</script>

nopCommerce-develop/src/Presentation/Nop.Web/Areas/Admin/Views/Shared/EditorTemplates/DecimalNullable.cshtml
@model Decimal?
<input asp-for="@Model" asp-format="{0:F4}" />
@{
    var postfix = "";
    if (ViewData.ContainsKey("postfix") && ViewData["postfix"] != null)
    {
        postfix = ViewData["postfix"].ToString();
    }
}
<script>
    $(document).ready(function() {
        $("#@Html.IdForModel()").TouchSpin({
            min: @Html.Raw(decimal.MinValue),
            max: @Html.Raw(decimal.MaxValue),
            decimals: 4, //always display 4 digits
            forcestepdivisibility: "none",
            verticalbuttons: true,
            verticalupclass: "glyphicon glyphicon-chevron-up",
            verticaldownclass: "glyphicon glyphicon-chevron-down",
            buttondown_class: "btn",
            buttonup_class: "btn",
            postfix: "@postfix"
        });
    });
</script>

nopCommerce-develop/src/Presentation/Nop.Web/Areas/Admin/Views/Shared/EditorTemplates/Double.cshtml
@model Double
<input asp-for="@Model"/>
@{
    var postfix = "";
    if (ViewData.ContainsKey("postfix") && ViewData["postfix"] != null)
    {
        postfix = ViewData["postfix"].ToString();
    }
}
<script>
    $(document).ready(function() {
        $("#@Html.IdForModel()").TouchSpin({
            min: @Html.Raw(double.MinValue),
            max: @Html.Raw(double.MaxValue),
            decimals: 4, //always display 4 digits
            forcestepdivisibility: "none",
            verticalbuttons: true,
            verticalupclass: "glyphicon glyphicon-chevron-up",
            verticaldownclass: "glyphicon glyphicon-chevron-down",
            buttondown_class: "btn",
            buttonup_class: "btn",
            postfix: "@postfix"
        });
    });
</script>

nopCommerce-develop/src/Presentation/Nop.Web/Areas/Admin/Views/Shared/EditorTemplates/Int32.cshtml
@model Int32
<input asp-for="@Model"/>
@{
    var postfix = "";
    if (ViewData.ContainsKey("postfix") && ViewData["postfix"] != null)
    {
        postfix = ViewData["postfix"].ToString();
    }
}
<script>
    $(document).ready(function() {
        $("#@Html.IdForModel()").TouchSpin({
            min: @Html.Raw(int.MinValue),
            max: @Html.Raw(int.MaxValue),
            decimals: 0,
            verticalbuttons: true,
            verticalupclass: "glyphicon glyphicon-chevron-up",
            verticaldownclass: "glyphicon glyphicon-chevron-down",
            buttondown_class: "btn",
            buttonup_class: "btn",
            postfix: "@postfix"
        });
    });
</script>

nopCommerce-develop/src/Presentation/Nop.Web/Areas/Admin/Views/Shared/EditorTemplates/Int32Nullable.cshtml
@model Int32?
<input asp-for="@Model"/>
@{
    var postfix = "";
    if (ViewData.ContainsKey("postfix") && ViewData["postfix"] != null)
    {
        postfix = ViewData["postfix"].ToString();
    }
}
<script>
    $(document).ready(function() {
        $("#@Html.IdForModel()").TouchSpin({
            min: @Html.Raw(int.MinValue),
            max: @Html.Raw(int.MaxValue),
            decimals: 0,
            verticalbuttons: true,
            verticalupclass: "glyphicon glyphicon-chevron-up",
            verticaldownclass: "glyphicon glyphicon-chevron-down",
            buttondown_class: "btn",
            buttonup_class: "btn",
            postfix: "@postfix"
        });
    });
</script>