nopCommerce-develop/src/Plugins/Nop.Plugin.Payments.Qualpay/Controllers/QualpayController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Core;
using Nop.Plugin.Payments.Qualpay.Domain;
using Nop.Plugin.Payments.Qualpay.Models;
using Nop.Plugin.Payments.Qualpay.Services;
using Nop.Services;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Controllers;
using Nop.Web.Framework.Controllers;

namespace Nop.Plugin.Payments.Qualpay.Controllers
{
    public class QualpayController : BaseAdminController
    {
        #region Fields

        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;
        private readonly QualpayManager _qualpayManager;

        #endregion

        #region Ctor

        public QualpayController(ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            IStoreContext storeContext,
            ISettingService settingService,
            QualpayManager qualpayManager)
        {
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _settingService = settingService;
            _storeContext = storeContext;
            _qualpayManager = qualpayManager;
        }

        #endregion

        #region Methods

        public IActionResult Configure()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeId = _storeContext.ActiveStoreScopeConfiguration;
            var settings = _settingService.LoadSetting<QualpaySettings>(storeId);

            //prepare model
            var model = new ConfigurationModel
            {
                MerchantId = settings.MerchantId,
                MerchantEmail = settings.MerchantEmail,
                SecurityKey = settings.SecurityKey,
                ProfileId = settings.ProfileId,
                UseSandbox = settings.UseSandbox,
                UseEmbeddedFields = settings.UseEmbeddedFields,
                UseCustomerVault = settings.UseCustomerVault,
                UseRecurringBilling = settings.UseRecurringBilling,
                PaymentTransactionTypeId = (int)settings.PaymentTransactionType,
                AdditionalFee = settings.AdditionalFee,
                AdditionalFeePercentage = settings.AdditionalFeePercentage,
                ActiveStoreScopeConfiguration = storeId,
                IsConfigured = !string.IsNullOrEmpty(settings.MerchantId) && long.TryParse(settings.MerchantId, out var merchantId)
            };

            if (storeId > 0)
            {
                model.UseSandbox_OverrideForStore = _settingService.SettingExists(settings, x => x.UseSandbox, storeId);
                model.UseEmbeddedFields_OverrideForStore = _settingService.SettingExists(settings, x => x.UseEmbeddedFields, storeId);
                model.UseCustomerVault_OverrideForStore = _settingService.SettingExists(settings, x => x.UseCustomerVault, storeId);
                model.UseRecurringBilling_OverrideForStore = _settingService.SettingExists(settings, x => x.UseRecurringBilling, storeId);
                model.PaymentTransactionTypeId_OverrideForStore = _settingService.SettingExists(settings, x => x.PaymentTransactionType, storeId);
                model.AdditionalFee_OverrideForStore = _settingService.SettingExists(settings, x => x.AdditionalFee, storeId);
                model.AdditionalFeePercentage_OverrideForStore = _settingService.SettingExists(settings, x => x.AdditionalFeePercentage, storeId);
            }

            //prepare payment transaction types
            model.PaymentTransactionTypes = TransactionType.Authorization.ToSelectList(false)
                .Select(item => new SelectListItem(item.Text, item.Value)).ToList();

            return View("~/Plugins/Payments.Qualpay/Views/Configure.cshtml", model);
        }

        [HttpPost, ActionName("Configure")]
        [FormValueRequired("save")]
        public IActionResult Configure(ConfigurationModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return Configure();

            //load settings for a chosen store scope
            var storeId = _storeContext.ActiveStoreScopeConfiguration;
            var settings = _settingService.LoadSetting<QualpaySettings>(storeId);

            //ensure that webhook is already exists and create the new one if does not (required for recurring billing)
            if (model.UseRecurringBilling)
            {
                var webhook = _qualpayManager.CreateWebhook(settings.WebhookId);
                if (webhook?.WebhookId != null)
                {
                    settings.WebhookId = webhook.WebhookId.ToString();
                    settings.WebhookSecretKey = webhook.Secret;
                    _settingService.SaveSetting(settings, x => x.WebhookId, storeId, false);
                    _settingService.SaveSetting(settings, x => x.WebhookSecretKey, storeId, false);
                }
                else
                    _notificationService.WarningNotification(_localizationService.GetResource("Plugins.Payments.Qualpay.Fields.Webhook.Warning"));
            }

            //save settings
            settings.MerchantId = model.MerchantId;
            settings.SecurityKey = model.SecurityKey;
            settings.ProfileId = model.ProfileId;
            settings.UseSandbox = model.UseSandbox;
            settings.UseEmbeddedFields = model.UseEmbeddedFields;
            settings.UseCustomerVault = model.UseCustomerVault;
            settings.UseRecurringBilling = model.UseRecurringBilling;
            settings.PaymentTransactionType = (TransactionType)model.PaymentTransactionTypeId;
            settings.AdditionalFee = model.AdditionalFee;
            settings.AdditionalFeePercentage = model.AdditionalFeePercentage;

            _settingService.SaveSetting(settings, x => x.MerchantId, storeId, false);
            _settingService.SaveSetting(settings, x => x.SecurityKey, storeId, false);
            _settingService.SaveSetting(settings, x => x.ProfileId, storeId, false);
            _settingService.SaveSettingOverridablePerStore(settings, x => x.UseSandbox, model.UseSandbox_OverrideForStore, storeId, false);
            _settingService.SaveSettingOverridablePerStore(settings, x => x.UseEmbeddedFields, model.UseEmbeddedFields_OverrideForStore, storeId, false);
            _settingService.SaveSettingOverridablePerStore(settings, x => x.UseCustomerVault, model.UseCustomerVault_OverrideForStore, storeId, false);
            _settingService.SaveSettingOverridablePerStore(settings, x => x.UseRecurringBilling, model.UseRecurringBilling_OverrideForStore, storeId, false);
            _settingService.SaveSettingOverridablePerStore(settings, x => x.PaymentTransactionType, model.PaymentTransactionTypeId_OverrideForStore, storeId, false);
            _settingService.SaveSettingOverridablePerStore(settings, x => x.AdditionalFee, model.AdditionalFee_OverrideForStore, storeId, false);
            _settingService.SaveSettingOverridablePerStore(settings, x => x.AdditionalFeePercentage, model.AdditionalFeePercentage_OverrideForStore, storeId, false);

            _settingService.ClearCache();

            //display notification
            _notificationService.SuccessNotification(_localizationService.GetResource("Admin.Plugins.Saved"));

            return Configure();
        }

        [HttpPost, ActionName("Configure")]
        [FormValueRequired("subscribe")]
        public IActionResult Subscribe(ConfigurationModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            //load settings
            var settings = _settingService.LoadSetting<QualpaySettings>();
            if (settings.MerchantEmail == model.MerchantEmail)
                return Configure();

            //try to subscribe/unsubscribe
            var (success, errorMessage) = _qualpayManager.SubscribeForQualpayNews(model.MerchantEmail);
            if (success)
            {
                //save settings and display success notification
                settings.MerchantEmail = model.MerchantEmail;
                _settingService.SaveSetting(settings);

                var message = !string.IsNullOrEmpty(model.MerchantEmail)
                    ? _localizationService.GetResource("Plugins.Payments.Qualpay.Subscribe.Success")
                    : _localizationService.GetResource("Plugins.Payments.Qualpay.Unsubscribe.Success");
                _notificationService.SuccessNotification(message);
            }
            else
            {
                var message = !string.IsNullOrEmpty(errorMessage)
                    ? errorMessage
                    : _localizationService.GetResource("Plugins.Payments.Qualpay.Subscribe.Error");

                _notificationService.ErrorNotification(message);
            }

            return Configure();
        }

        #endregion
    }
}

nopCommerce-develop/src/Plugins/Nop.Plugin.Payments.Qualpay/Views/Configure.cshtml
@model Nop.Plugin.Payments.Qualpay.Models.ConfigurationModel;

@{
    Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="Qualpay" asp-action="Configure" method="post">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <p>
                    Please enter your email to receive an information about special offers from Qualpay
                </p>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="MerchantEmail" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="MerchantEmail" />
                        <span asp-validation-for="MerchantEmail"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="subscribe" class="btn btn-primary" value="@T("Plugins.Payments.Qualpay.Subscribe")" />
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <p>
                    To configure the Qualpay plugin for nopCommerce.<br />
                    <br />
                    1. Decide if you'd like to run Sandbox (test) or Production (live) transactions.<br />
                    2. If you don't have a Qualpay account, use the links below to create one.<br />
                        &emsp;a. <a href="https://app-test.qualpay.com/login/signup" target="_blank">Sign up for a Qualpay sandbox account</a>.<br />
                        &emsp;b. <a href="https://www.qualpay.com/get-started/nopcommerce " target="_blank">Apply for a Qualpay production account</a>.<br />
                    3. Log into either the <a href="https://app-test.qualpay.com" target="_blank">Qualpay sandbox</a> or <a href="https://app.qualpay.com" target="_blank">Qualpay production</a> environment to retrieve your security keys.<br />
                    4. On the main menu to the left, select "Administration" then "API Security Keys".<br />
                    5. In the "Key Detail" section, locate your Merchant ID and click the clipboard icon to copy your merchant ID.<br />
                    6. Paste your Merchant ID below in the Merchant ID field.<br />
                    7. In "Manage Access" enable the following API's<br />
                        &emsp;a. Payment Gateway API<br />
                        &emsp;b. Embedded Fields API<br />
                        &emsp;c. Customer Vault API<br />
                        &emsp;d. Recurring Billing API<br />
                        &emsp;e. Webhook API<br />
                    8. Click "Generate".<br />
                    9. Click on the clipboard icon to copy your Security Key.<br />
                    10. Paste your Security Key below.<br />
                    11. Save the configuration.<br />
                </p>
                <p>
                    <em>Notes:</em><br />
                    For this plugin to work properly ensure that you have set your primary store currency to USD.<br />
                    Qualpay Sandbox (test) or Production (live) are unique. For example, you may not use a Sandbox (test) Merchant ID and Security Key to run Production (live) transactions.<br />
                </p>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="MerchantId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="MerchantId" asp-required="true" />
                        <span asp-validation-for="MerchantId"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="SecurityKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="SecurityKey" asp-required="true" />
                        <span asp-validation-for="SecurityKey"></span>
                    </div>
                </div>
                @if (Model.IsConfigured)
                {
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-override-store-checkbox asp-for="UseSandbox_OverrideForStore" asp-input="UseSandbox" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                            <nop-label asp-for="UseSandbox" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="UseSandbox" />
                            <span asp-validation-for="UseSandbox"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-override-store-checkbox asp-for="UseEmbeddedFields_OverrideForStore" asp-input="UseEmbeddedFields" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                            <nop-label asp-for="UseEmbeddedFields" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="UseEmbeddedFields" />
                            <span asp-validation-for="UseEmbeddedFields"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-override-store-checkbox asp-for="UseCustomerVault_OverrideForStore" asp-input="UseCustomerVault" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                            <nop-label asp-for="UseCustomerVault" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="UseCustomerVault" />
                            <span asp-validation-for="UseCustomerVault"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-override-store-checkbox asp-for="UseRecurringBilling_OverrideForStore" asp-input="UseRecurringBilling" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                            <nop-label asp-for="UseRecurringBilling" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="UseRecurringBilling" />
                            <span asp-validation-for="UseRecurringBilling"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="ProfileId" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="ProfileId" />
                            <span asp-validation-for="ProfileId"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-override-store-checkbox asp-for="PaymentTransactionTypeId_OverrideForStore" asp-input="PaymentTransactionTypeId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                            <nop-label asp-for="PaymentTransactionTypeId" />
                        </div>
                        <div class="col-md-9">
                            <nop-select asp-for="PaymentTransactionTypeId" asp-items="Model.PaymentTransactionTypes" />
                            <span asp-validation-for="PaymentTransactionTypeId"></span>
                        </div>
                    </div>
                }
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AdditionalFee_OverrideForStore" asp-input="AdditionalFee" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AdditionalFee" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalFee" />
                        <span asp-validation-for="AdditionalFee"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AdditionalFeePercentage_OverrideForStore" asp-input="AdditionalFeePercentage" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AdditionalFeePercentage" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalFeePercentage" />
                        <span asp-validation-for="AdditionalFeePercentage"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="save" class="btn btn-primary" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

nopCommerce-develop/src/Plugins/Nop.Plugin.Payments.Qualpay/Views/PaymentInfo.cshtml
@model Nop.Plugin.Payments.Qualpay.Models.PaymentInfoModel

@inject Nop.Core.Domain.Orders.OrderSettings orderSettings
@inject Nop.Plugin.Payments.Qualpay.QualpaySettings qualpaySettings

@{
    Layout = "";
    Html.AddScriptParts(ResourceLocation.Footer, Nop.Plugin.Payments.Qualpay.QualpayDefaults.EmbeddedFieldsScriptPath, excludeFromBundle: true);
    Html.AddCssFileParts(Nop.Plugin.Payments.Qualpay.QualpayDefaults.EmbeddedFieldsStylePath, excludeFromBundle: true);
}

<script asp-location="Footer">
    $(document).ready(function() {
        $("#@Html.IdFor(model => model.BillingCardId)").change(toggleBillingCard);
        toggleBillingCard();

@if (qualpaySettings.UseEmbeddedFields)
{
    <text>
        $('.section.payment-info').before('<form id="qualpay-payment-form"><input type="submit" id="qualpay-payment-form-submit" style="display: none" /></form>');

        var submitForm = false;
        var errorsExist = false;
        var stepBack = false;
        var onePageCheckout = @orderSettings.OnePageCheckoutEnabled.ToString().ToLower();
        $('.payment-info-next-step-button').attr('onclick', null);
        $('.payment-info-next-step-button').prop('disabled', true);
        $('.payment-info-next-step-button').css("opacity", .3);

        var configurationParams = {
            formId: 'qualpay-payment-form',
            mode: '@(qualpaySettings.UseSandbox ? "test" : "prod")',
            transientKey: '@Model.TransientKey',
            tokenize: false,
            onSuccess: (data) => {
                $('#@Html.IdFor(model => model.TokenizedCardId)').val(data.card_id);
                submitForm = true;
                $('input.payment-info-next-step-button').click();
            },
            onError: (error) => {
                qpEmbeddedForm.unloadFrame();
                if (error.msg) {
                    var currentErrorvalue = $('#@Html.IdFor(model => model.Errors)').val();
                    $('#@Html.IdFor(model => model.Errors)').val(currentErrorvalue + '|' + error.msg);
                }
                if (error.detail) {
                    error.detail.forEach(function (detail) {
                        var currentErrorvalue = $('#@Html.IdFor(model => model.Errors)').val();
                        $('#@Html.IdFor(model => model.Errors)').val(currentErrorvalue + '|' + detail);
                    });
                }
                errorsExist = true;
                submitForm = true;
                $('input.payment-info-next-step-button').click();
            }
        };

        if (!stepBack) {
            qpEmbeddedForm.loadFrame('@qualpaySettings.MerchantId', configurationParams);
        }
        else {
            qpEmbeddedForm.unloadFrame();
        }

        $('input.payment-info-next-step-button').on('click', function (data) {
            var selectedBillingCardId = $('#@Html.IdFor(model => model.BillingCardId)').val();
            if (!submitForm && (!selectedBillingCardId || selectedBillingCardId == '@Guid.Empty.ToString()')) {
                if (!errorsExist && !stepBack) {
                    $('#qualpay-payment-form-submit').click();
                }
                return false;
            }
            else if (onePageCheckout) {
                submitForm = false;
                PaymentInfo.save();
            }
        });

        $(document).on('accordion_section_opened', function (data) {
            if (data && (data.currentSectionId == 'opc-billing' || data.currentSectionId == 'opc-shipping' || data.currentSectionId == 'opc-shipping_method' || data.currentSectionId == 'opc-payment_method')) {
                stepBack = true;
            }
        });

        $("#qp-embedded-frame").on("load", function () {
            $('.payment-info-next-step-button').prop('disabled', false);
            $('.payment-info-next-step-button').css("opacity", 1);
        });

        $(window).on("beforeunload", function() {
            qpEmbeddedForm.unloadFrame();
        });
    </text>
}
    });

    function toggleBillingCard() {
        var selectedBillingCardId = $('#@Html.IdFor(model => model.BillingCardId)').val();
        if (!selectedBillingCardId || selectedBillingCardId == '@Guid.Empty.ToString()') {
            $('#qualpay-card-details').show();
        } else {
            $('#qualpay-card-details').hide();
        }
    }
</script>

@if (qualpaySettings.UseCustomerVault && !Model.IsGuest && Model.BillingCards.Any())
{
    <table width="100%" cellspacing="2" cellpadding="1" border="0">
        <tr>
            <td>
                <label asp-for="BillingCardId">@T("Plugins.Payments.Qualpay.Customer.Card"):</label>
            </td>
            <td>
                <select asp-for="BillingCardId" asp-items="Model.BillingCards" class="dropdownlists"></select>
                <span asp-validation-for="BillingCardId"></span>
            </td>
        </tr>
    </table>
}

<table width="100%" cellspacing="2" cellpadding="1" border="0" id="qualpay-card-details">
    <style type='text/css'>
        @@media (max-width: 422px) {
            #qp-embedded-container {
                height: 12em;
            }
        }
    </style>
    @if (qualpaySettings.UseEmbeddedFields)
    {
        <tr>
            <td>
                <input type="hidden" asp-for="TokenizedCardId">
                <input type="hidden" asp-for="Errors">
            </td>
            <td>
                <div id="qp-embedded-container" align="center"></div>
            </td>
        </tr>
    }
    else
    {
        <tr>
            <td>
                <label asp-for="CardholderName">@T("Payment.CardholderName"):</label>
            </td>
            <td>
                <input type="text" asp-for="CardholderName" style="width: 165px;" autocomplete="off" />
                <span asp-validation-for="CardholderName"></span>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="CardNumber">@T("Payment.CardNumber"):</label>
            </td>
            <td>
                <input type="text" asp-for="CardNumber" style="width: 165px;" autocomplete="off" maxlength="22" />
                <span asp-validation-for="CardNumber"></span>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="ExpireMonth">@T("Payment.ExpirationDate"):</label>
            </td>
            <td>
                <select asp-for="ExpireMonth" asp-items="Model.ExpireMonths"></select>
                /
                <select asp-for="ExpireYear" asp-items="Model.ExpireYears"></select>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="CardCode">@T("Payment.CardCode"):</label>
            </td>
            <td>
                <input type="text" asp-for="CardCode" style="width: 60px;" autocomplete="off" maxlength="4" />
                <span asp-validation-for="CardCode"></span>
            </td>
        </tr>
    }
    @if (qualpaySettings.UseCustomerVault && !Model.IsGuest && !Model.IsRecurringOrder)
    {
        <tr>
            <td>
                <label asp-for="SaveCardDetails">@T("Plugins.Payments.Qualpay.Customer.Card.Save"):</label>
            </td>
            <td>
                <input type="checkbox" asp-for="SaveCardDetails" />
                <span asp-validation-for="SaveCardDetails"></span>
            </td>
        </tr>
    }
</table>

@Html.NopInlineScripts(ResourceLocation.Footer)